version: "3.6"
services:
    # The caddy server is a lightning fast web server written in Go.
    cpmr-caddy:
        # image: registry.gitlab.com/andersonpem/caddy-php-fpm-mysql-redis:caddy-latest
        build:
            context: .
            dockerfile: ./.docker/Caddy/Dockerfile
        ports:
            - ${CADDY_HTTP_PORT}:80
            - ${CADDY_HTTPS_PORT}:443
            # - 6001:6001
        volumes:
            - ./.docker/Caddy/Caddyfile:/etc/caddy/Caddyfile:rw
            - ./code:/var/www/html
        environment: 
            REMOTE_PORT: 80
            TZ: "America/Sao_Paulo"
            CADDY_SERVER_HOST: ${CADDY_SERVER_HOST}
            DOCUMENT_ROOT: ${DOCUMENT_ROOT}
    cpmr-php-fpm:
        # image: thecodingmachine/php:7.4-v3-fpm
        build: 
            context: .
            dockerfile: ./.docker/php-fpm/Dockerfile
        restart: always
        # ports: 
        #     - 9000:9000
        volumes:
            - ./code:/var/www/html
        environment:
#           General settings
            #Ext enable
            PHP_EXTENSIONS: ${PHP_EXTENSIONS}
            TZ: ${TZ}
            TEMPLATE_PHP_INI: ${TEMPLATE_PHP_INI}

            #PHP.ini settings
            PHP_INI_UPLOAD_MAX_FILESIZE: ${PHP_INI_UPLOAD_MAX_FILESIZE}
            PHP_INI_MAX_EXECUTION_TIME: ${PHP_INI_MAX_EXECUTION_TIME}
            PHP_INI_MEMORY_LIMIT: ${PHP_INI_MEMORY_LIMIT}
            PHP_INI_DATE__TIMEZONE: ${TZ}
            APACHE_DOCUMENT_ROOT: ${DOCUMENT_ROOT}
#           Debug only
            PHP_EXTENSION_XDEBUG: ${PHP_EXTENSION_XDEBUG}
            PHP_INI_XDEBUG__REMOTE_ENABLE: ${PHP_INI_XDEBUG__REMOTE_ENABLE}
            PHP_INI_XDEBUG__REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
            PHP_INI_XDEBUG__REMOTE_HANDLER: "dbgp"
            PHP_INI_XDEBUG__REMOTE_PORT: ${PHP_INI_XDEBUG__REMOTE_PORT}
            PHP_INI_XDEBUG__REMOTE_AUTOSTART: "1"
            PHP_INI_XDEBUG__REMOTE_CONNECT_BACK: "on"
            PHP_INI_XDEBUG__IDEKEY: ${PHP_INI_XDEBUG__IDEKEY}
            # PHP_INI_XDEBUG__REMOTE_LOG: "xdebug.log"
            PHP_INI_ERROR_REPORTING: ${PHP_INI_ERROR_REPORTING}
            #Production Settings
            # TEMPLATE_PHP_INI: production
            DOCKER_USER: ${DOCKER_USER}
            APACHE_RUN_USER: ${APACHE_RUN_USER}
            APACHE_RUN_GROUP: ${APACHE_RUN_GROUP}

    cpmr-mysql:
        image: mysql:8
        restart: unless-stopped
        ports:
            - ${MYSQL_PORT}:3306
        volumes:
            - ./data/mysql:/var/lib/mysql:delegated
            - ./.docker/Mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=$MYSQL_PASSWORD
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - ${TZ}
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    cpmr-redis:
        # image: redis:latest
        build: 
            context: .
            dockerfile: ./.docker/Redis/Dockerfile
        volumes:
            - ./data/redis:/data
            - ./.docker/Redis/redis.conf:/etc/redis/redis.conf
        ports:
            - "${REDIS_PORT}:6379"
        secrets:
            - redis_secret
    # cpmr-adminer:
    #     image: adminer
    #     ports:
    #         - 8080:8080
#    redisinsight:
#        image: redislabs/redisinsight
#        # volumes:
#            # - ./data/redisinsight:/db
#        ports:
#            - 8001:8001
secrets:
    redis_secret:
        file: ./redis-secret.txt
              





        