version: "3.8"
services:
    # The caddy server is a lightning fast web server written in Go.
    cpmr-caddy:
        container_name: app-caddy
        # image: registry.gitlab.com/andersonpem/caddy-php-fpm-mysql-redis:caddy-latest
        build:
            context: .
            dockerfile: ./.docker/Caddy/Dockerfile
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./.docker/Caddy/Caddyfile:/etc/caddy/Caddyfile:rw
            - ./code:/var/www/html
        environment: 
            REMOTE_PORT: 80
    cpmr-php-fpm:
        # image: thecodingmachine/php:7.4-v3-fpm
        build: 
            context: .
            dockerfile: ./.docker/php-fpm/Dockerfile
        restart: always
        # ports: 
        #     - 9000:9000
        volumes:
            - ./code:/var/www/html
        environment:
#           General settings
            #Ext enable
            PHP_EXTENSIONS: ctype curl dom mbstring intl xml xmlreader xmlwriter redis gd bcmath bz2 yaml
            # TEMPLATE_PHP_INI: production

            #PHP.ini settings
            PHP_INI_UPLOAD_MAX_FILESIZE: 200M
            PHP_INI_MAX_EXECUTION_TIME: 300
            PHP_INI_MEMORY_LIMIT: 1G
#           Change this if the document root is not /var/www/html
            APACHE_DOCUMENT_ROOT: /var/www/html/public
#           Debug only
            PHP_EXTENSION_XDEBUG: 1
            PHP_INI_XDEBUG__REMOTE_ENABLE: "on"
            PHP_INI_XDEBUG__REMOTE_HOST: host.docker.internal
            PHP_INI_XDEBUG__REMOTE_HANDLER: "dbgp"
            PHP_INI_XDEBUG__REMOTE_PORT: 9000
            PHP_INI_XDEBUG__REMOTE_AUTOSTART: "1"
            PHP_INI_XDEBUG__REMOTE_CONNECT_BACK: "on"
            PHP_INI_XDEBUG__IDEKEY: "docker"
            # PHP_INI_XDEBUG__REMOTE_LOG: "xdebug.log"
            PHP_INI_ERROR_REPORTING: E_ALL
            #Production Settings
            # TEMPLATE_PHP_INI: production
            # DOCKER_USER: www-data
            # APACHE_RUN_USER: www-data
            # APACHE_RUN_GROUP: www-data

    cpmr-mysql:
        image: mysql:8
        restart: unless-stopped
        ports:
            - 3306:3306
        volumes:
            - ./data/mysql:/var/lib/mysql:delegated
            - ./.docker/Mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=homestead
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=root
            - TZ=America/Sao_Paulo
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    cpmr-redis:
        # image: redis:latest
        build: 
            context: .
            dockerfile: ./.docker/Redis/Dockerfile
        volumes:
            - ./data/redis:/data
            - ./.docker/Redis/redis.conf:/etc/redis/redis.conf
        ports:
            - "6379:6379"
        secrets:
            - redis_secret
    cpmr-adminer:
        image: adminer
        ports:
            - 8080:8080
#    redisinsight:
#        image: redislabs/redisinsight
#        # volumes:
#            # - ./data/redisinsight:/db
#        ports:
#            - 8001:8001
secrets:
    redis_secret:
        file: ./redis-secret.txt
              





        